export const GET_TYPES = 'GET_TYPES'
export const GET_ALL_POKEMONS= 'GET_ALL_POKEMONS'
export const GET_POKEMON_BY_ID= 'GET_POKEMON_BY_ID'
export const GET_POKEMON_BY_NAME= 'GET_POKEMON_BY_NAME'
export const CLEAR= 'CLEAR'
export const FILTER_ORDER='FILTER_ORDER'
export const MEMORY='MEMORY'
export const ALL_ID='ALL_ID'
export const ALL_NAMES='ALL_NAMES'

